DECLARE @DATE DATE
,@DAYNO INT
,@NEWNO INT
,@NEXTWEEKNO INT=3

SET @NEXTWEEKNO =( @NEXTWEEKNO*7)+1
SET @DATE= CONVERT(DATE,'02-07-2017') 
SET @DAYNO= DATEPART(DW,@DATE) 


		IF(@DAYNO>2)
		BEGIN 	
			SET @NEWNO= (30-(@NEXTWEEKNO+@DAYNO) )+@NEXTWEEKNO	
		END

		IF( @DAYNO =2)
		BEGIN 	
			SET @NEWNO= @NEXTWEEKNO-1	
		END

		IF( @DAYNO =1)
		BEGIN 		
		SET @NEWNO= @NEXTWEEKNO	
		END


SELECT DATENAME(DW,DATEADD(D,@NEWNO,@DATE))  AS DAY_NAME, DATEADD(D,@NEWNO,@DATE) AS DATENEXT
